title: Loyalty20 Rewards Programs
logo: /assets/img/logo.jpg
description: Loyalty Rewards Programs using Cryptocurrency 
show_downloads: true  
google_analytics: wooriapt79
theme: jekyll-theme-minimal

# Site Author
author:
  name: Blockchain Lab
  avatar: Lab
  bio: Your biography for the left-hand sidebar
  location: Korea
